<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<meta name="description" content="The Netwide Assembler (NASM) is an assembler and disassembler for the Intel x86 architecture, used by developers worldwide">
	<meta name="author" content="Netwide Assembler (NASM) Team">
	<meta name="keywords" content="NASM, assembler, assembly language">

	<title>NASM</title>

	<link href="css/bootstrap.min.css" rel="stylesheet">
	<link href="css/web-fonts.css" rel="stylesheet">
	<link href="css/nasm.css" rel="stylesheet">
</head>
<?php $domain = preg_replace('/^www\./', '', $_SERVER['SERVER_NAME']); ?>
