<!-- The comment markers are needed here, due to the polyglotness hack -->
<!-- <?php
require('./version.inc');
?> -->

<nav class="navbar navbar-default" role="navigation">
	<div class="container-fluid container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-id">
				<span class="sr-only">Toggle</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="index.php">NASM</a>
		</div>

		<div class="collapse navbar-collapse navbar-right" id="navbar-collapse-id">
			<ul class="nav navbar-nav">
				<li><a href="https://forum.nasm.us">Forum</a></li>
				<li><a href="https://www.nasm.us/pub/nasm/releasebuilds/?C=M;O=D">Download</a></li>
				<li><a href="https://github.com/netwide-assembler/nasm.git">Repo</a></li>
				<li><a href="docs.php">Docs</a></li>
				<li><a href="http://bugzilla.nasm.us">Bugs</a></li>
				<li><a href="patches.php">Patches</a></li>
				<li><a href="https://lists.nasm.us/">Lists</a></li>
			</ul>
		</div>
	</div>
</nav>
