<div id="nav">
 <ul>
  <li><a href="http://nasm.sourceforge.net/">Home</a></li>
  <li><a href="http://sourceforge.net/news/?group_id=6208">News</a></li>
  <li><a href="http://sourceforge.net/forum/?group_id=6208">Forum</a></li>
  <li><a href="http://sourceforge.net/project/showfiles.php?group_id=6208">Download</a></li>
  <li><a href="http://repo.or.cz/w/nasm.git">GIT Repository</a></li>
  <li><a href="ftp://ftp.zytor.com/pub/nasm/snapshots/">Snapshots</a></li>
  <li><a href="/doc/">Documentation</a></li>
  <li><a href="http://sourceforge.net/tracker/?atid=106208&amp;group_id=6208&amp;func=browse">Bug Tracker</a></li>
  <li><a href="http://nasm.sourceforge.net/links.php">Related Links</a></li>
  <li><a href="http://sourceforge.net/project/memberlist.php?group_id=6208">Credits</a></li>
 </ul>
</div>
