<?php /* -*- html -*- */ ?>
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse-id">
	<span class="sr-only">Toggle</span>
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
	<span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">
	<img src="images/nasm.png" alt="NASM Logo" class="navbar-logo">
      </a>
    </div>

    <div class="collapse navbar-collapse navbar-right" id="navbar-collapse-id">
      <ul class="nav navbar-nav">
	<li><a href="https://forum.<?=$domain?>">Forum</a></li>
	<li><a href="/pub/nasm/releasebuilds/?C=M;O=D">Download</a></li>
	<li><a href="/links/repo">Repo</a></li>
	<li><a href="/docs.html">Docs</a></li>
	<li><a href="https://bugzilla.<?=$domain?>/">Bugs</a></li>
	<li><a href="/patches.html">Patches</a></li>
	<li><a href="https://lists.<?=$domain?>/">Lists</a></li>
      </ul>
    </div>
  </div>
</nav>
